### ISSUE TITLE
关于动画方便的提议，addEffect目前只能增加一次动画

### ISSUE THREAD

**Issue by w5w6** [tnfe/FFCreatorLite#2]
很高兴可以尝试到这么棒的开源产品，我在知道FFCreatorLite的时候，第一时间进行了尝试。
使用中，我发现addEffect只支持一个动画，在实际使用中不太友好。

建议可以这样：
`img.addEffect[{'zoomNopadIn', 1, 1}, {'rotateInBig', 1.5, 1.5}]`
或者
`img.addEffect('zoomNopadIn', 1.5, 0)
img.addEffect('rotateInBig', 1.5, 1.5);`

如果可以这样，动画方便会很棒哦！

**Comment by drawcall** [comment]
Oh thank you, yes FFCreatorLite currently does not support adding multiple `addEffect`, because FFCreatorLite implements animation by segmenting ffmpeg parameter instructions, it is very complicated to add multiple effects. I recommend you to use [FFCreator] (https://github.com/tnfe/FFCreator) It has more powerful and flexible animation support, which can meet your needs

**Comment by w5w6** [comment]
@drawcall 谢谢，我去试一下
